In [3]:
from google.colab import files
import pandas as pd

#Extraccion dataset delitos informáticos 1
uploaded = files.upload()

file_name = list(uploaded.keys())[0]

df_delitos_informaticos1 = pd.read_csv(file_name)

df_delitos_informaticos1.head()

Saving Delitos_Informaticos_V1_20260312.csv to Delitos_Informaticos_V1_20260312.csv

,CRIMINALIDAD,ES_ARCHIVO,ES_PRECLUSIÓN,ESTADO,ETAPA_CASO,LEY,PAÍS_HECHO,DEPARTAMENTO_HECHO,MUNICIPIO_HECHO,SECCIONAL,AÑO_HECHOS,AÑO_ENTRADA,AÑO_DENUNCIA,DELITO,GRUPO_DELITO,CONSUMADO,TOTAL_PROCESOS
0,SI,NO,NO,ACTIVO,INDAGACIÓN,Ley 906,Colombia,Caquetá,FLORENCIA,DIRECCIÓN SECCIONAL DE CAQUETÁ,2025,2025,2025,HURTO POR MEDIOS INFORMATICOS Y SEMEJANTES ART...,DELITOS INFORMATICOS,NO APLICA,99
1,NO,SI,NO,INACTIVO,INDAGACIÓN,Ley 906,Colombia,Cesar,VALLEDUPAR,DIRECCIÓN SECCIONAL DE CESAR,2014,2015,2015,SUPLANTACION DE SITIOS WEB PARA CAPTURAR DATOS...,DELITOS INFORMATICOS,NO APLICA,1
2,SI,NO,NO,INACTIVO,INDAGACIÓN,Ley 906,Colombia,Nariño,TUMACO,DIRECCIÓN SECCIONAL DE NARIÑO,2025,2025,2025,ACCESO ABUSIVO A UN SISTEMA INFORMATICO ART 26...,DELITOS INFORMATICOS,NO APLICA,4
3,NO,SI,NO,INACTIVO,INDAGACIÓN,Ley 906,Colombia,"BOGOTÁ, D. C.","BOGOTÁ, D.C.",DIRECCIÓN SECCIONAL DE BOGOTÁ,2023,2023,2023,VIOLACION DE DATOS PERSONALES ART 269F LEY 127...,DELITOS INFORMATICOS,NO APLICA,124
4,SI,NO,NO,INACTIVO,INDAGACIÓN,Ley 906,Colombia,Magdalena,CIÉNAGA,DIRECCIÓN SECCIONAL DE MAGDALENA,2022,2022,2022,HURTO POR MEDIOS INFORMATICOS Y SEMEJANTES ART...,DELITOS INFORMATICOS,NO APLICA,5

In [5]:
#Extraccion dataset delitos informáticos 1
uploaded = files.upload()

file_name = list(uploaded.keys())[0]

df_delitos_informaticos2 = pd.read_csv(file_name)

Saving DELITOS_INFORMÁTICOS_20260312.csv to DELITOS_INFORMÁTICOS_20260312.csv

TypeError: 'DataFrame' object is not callable

In [6]:
df_delitos_informaticos2.head()

,FECHA HECHO,COD_DEPTO,DEPARTAMENTO,COD_MUNI,MUNICIPIO,DESCRIPCION CONDUCTA,CANTIDAD
0,2006 May 13 12:00:00 AM,11,BOGOTA D.C.,11001,BOGOTA D.C.,ARTICULO 269I. HURTO POR MEDIOS INFORMATICOS Y...,1
1,2006 Oct 06 12:00:00 AM,11,BOGOTA D.C.,11001,BOGOTA D.C.,ARTICULO 269A. ACCESO ABUSIVO A UN SISTEMA INF...,1
2,2008 May 24 12:00:00 AM,11,BOGOTA D.C.,11001,BOGOTA D.C.,ARTICULO 269A. ACCESO ABUSIVO A UN SISTEMA INF...,1
3,2009 Jan 01 12:00:00 AM,41,HUILA,41001,NEIVA,ARTICULO 269F. VIOLACION DE DATOS PERSONALES,1
4,2009 Jan 02 12:00:00 AM,11,BOGOTA D.C.,11001,BOGOTA D.C.,ARTICULO 269A. ACCESO ABUSIVO A UN SISTEMA INF...,1

In [11]:
from google.colab import files
import pandas as pd

uploaded = files.upload()

file_name = list(uploaded.keys())[0]

df = pd.read_excel(file_name, header=[7,8])

df.head()

Saving PPED-AreaSexoEdadReg-2018-2050 (1).xlsx to PPED-AreaSexoEdadReg-2018-2050 (1) (1).xlsx

        SIGLA REGIÓN                TERRITORIO                AÑO  \
  Unnamed: 0_level_1        Unnamed: 1_level_1 Unnamed: 2_level_1
0                ACB  Altiplano Cundiboyacense             2018.0
1                ACB  Altiplano Cundiboyacense             2018.0
2                ACB  Altiplano Cundiboyacense             2018.0
3                AMG            Alto Magdalena             2018.0
4                AMG            Alto Magdalena             2018.0

                     ÁREA GEOGRÁFICA      TOTAL                        \
                  Unnamed: 3_level_1      Total    Hombres    Mujeres
0                           Cabecera  1356448.0   652220.0   704228.0
1  Centros Poblados y Rural Disperso  1158498.0   603690.0   554808.0
2                              Total  2514946.0  1255910.0  1259036.0
3                           Cabecera   697780.0   336402.0   361378.0
4  Centros Poblados y Rural Disperso   535626.0   281194.0   254432.0

         HOMBRES                               ... TOTAL (AMBOS SEXOS)  \
  Hombres 0 años Hombres 1 año Hombres 2 años  ...       Total 91 años
0         9942.0       10163.0        10369.0  ...               954.0
1         7803.0        7886.0         8030.0  ...              1037.0
2        17745.0       18049.0        18399.0  ...              1991.0
3         6491.0        6628.0         6639.0  ...               464.0
4         6129.0        6084.0         5984.0  ...               235.0

                                                                         \
  Total 92 años Total 93 años Total 94 años Total 95 años Total 96 años
0         742.0         572.0         443.0         342.0         261.0
1         788.0         593.0         446.0         338.0         248.0
2        1530.0        1165.0         889.0         680.0         509.0
3         363.0         284.0         221.0         172.0         130.0
4         182.0         139.0         104.0          79.0          60.0


  Total 97 años Total 98 años Total 99 años Total 100 años  y más
0         199.0         142.0         103.0                 294.0
1         185.0         127.0          91.0                 262.0
2         384.0         269.0         194.0                 556.0
3          99.0          70.0          46.0                 145.0
4          46.0          31.0          23.0                  74.0

[5 rows x 310 columns]